#name: Python package
#
#on: [push]
#
#jobs:
#  build:
#
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        python-version: [3.6, 3.7, 3.8, 3.9]
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Python ${{ matrix.python-version }}
#        uses: actions/setup-python@v2
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install flake8 pytest
#          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#      - name: Lint with flake8
#        run: |
#          # stop the build if there are Python syntax errors or undefined names
#          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#      - name: Test with pytest
#        run: |
#          pytest
name: Django CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        include:
          - python-version: 3.6
            requirements: django_2_2
          - python-version: 3.7
            requirements: django_2_2
          - python-version: 3.8
            requirements: django_2_2
          - python-version: 3.9
            requirements: django_2_2

          - python-version: 3.6
            requirements: django_3_0
          - python-version: 3.7
            requirements: django_3_0
          - python-version: 3.8
            requirements: django_3_0
          - python-version: 3.9
            requirements: django_3_0

          - python-version: 3.6
            requirements: django_3_1
          - python-version: 3.7
            requirements: django_3_1
          - python-version: 3.8
            requirements: django_3_1
          - python-version: 3.9
            requirements: django_3_1

          - python-version: 3.6
            requirements: django_3_2
          - python-version: 3.7
            requirements: django_3_2
          - python-version: 3.8
            requirements: django_3_2
          - python-version: 3.9
            requirements: django_3_2

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        pip-compile examples/requirements/${{ matrix.requirements }}.in
        pip install -r examples/requirements/${{ matrix.requirements }}.txt
        pip-compile examples/requirements/test.in
        pip install -r examples/requirements/test.txt
    - name: Run Tests
      run: pytest

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.COVERALLS }}
        parallel-finished: true
